<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 2.2.5 on 2020-01-23 16:57

from django.db import migrations, models
=======
=======
>>>>>>> refs/remotes/origin/master
# Generated by Django 2.2.5 on 2020-01-21 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
<<<<<<< HEAD
>>>>>>> 37490fcfc9b9789a29ca4709225c286298a7f7bb
=======
>>>>>>> refs/remotes/origin/master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 37490fcfc9b9789a29ca4709225c286298a7f7bb
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> refs/remotes/origin/master
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
<<<<<<< HEAD
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
=======
=======
>>>>>>> refs/remotes/origin/master
            name='flag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_faille', models.IntegerField()),
                ('flag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flag1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Point1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
<<<<<<< HEAD
>>>>>>> 37490fcfc9b9789a29ca4709225c286298a7f7bb
=======
>>>>>>> refs/remotes/origin/master
        ),
    ]
