# Generated by Django 2.2.5 on 2020-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200123_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='email',
        ),
        migrations.AddField(
            model_name='myuser',
            name='nom',
            field=models.CharField(default='SOME STRING', max_length=20, unique=True, verbose_name='speudo'),
        ),
    ]
