# Generated by Django 3.0.2 on 2020-01-31 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200131_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='num_faille',
        ),
    ]
